### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-station#31]
I would like to have the electron app listening to 2 keyboard shortcuts:
- listen to {cmd, ctrl}+i+d - If a piece of text is selected and if that piece of text is a valid hash, it gets downloaded
- listen to {cmd, ctrl}+i+u - If a file or a group of files are selected, those files get uploaded

Does someone have opinions/thoughts on this? Maybe other hotkeys for better UX?

---

### Todo

- [ ] `ctrl+alt+u` = upload selected
- [x] `ctrl+alt+s` = screenshot upload
- [x] `ctrl+alt+d` = download hash selected

**Comment by jbenet** [comment]
veyr much :+1: to this. 

one thing: may not be able to do `+i+{d,u}` because those are letters, not modifiers. afaik keyboards dont like that?

**Comment by diasdavid** [comment]
More than one 'non modifier key' ref: https://github.com/atom/electron/issues/2486

**Comment by diasdavid** [comment]
Ok, can't do 2 key codes

Going for:
`ctrl+alt+u` = upload selected
`ctrl+alt+s` = screenshot upload
`ctrl+alt+d` = download hash selected

**Comment by hacdias** [comment]
Gonna start this 😄

**Comment by hacdias** [comment]
Updated the main comment https://github.com/ipfs-shipyard/ipfs-station/issues/31#issue-100265996

**Comment by hacdias** [comment]
@diasdavid what if you did `CTRL+C` on your hash and then `CTRL+ALT+D` to download the copied hash? (The same for uploading the files).

**Comment by hacdias** [comment]
Download the last copied hash is now working 😄 I don't know if we should let this opened or not. I can't find any "positive" information about reading files from the clipboard on Electron. /cc @diasdavid

**Comment by diasdavid** [comment]
👏🏽👏🏽👏🏽
